runtime:
  data: /home/mohammad/omni_inte/build/temp/output/final_runtime.csv
  tasks:
    - modules.resource_score.compute_rsm_task_all_regions
    - viz.sunburst3.sunburst
  name:  'runtime'
  target:  'runtime'
  compute_target: modules.compute_target.compute_inverse_target
##############################

main:
  tasks:
    - runtime
    - viz.dashboard.dashboard_init
  arch: amd-mi200
  data_rescale: true
  rsm_iters: 500
  rsm_print: false
  rsm_use_nn_solver: true
  use_belief: true
  compat_labels: true
  shorten_event_name: false
  port: 7603
