name: analysis_framework_env
channels:
    - conda-forge
dependencies:
    - pyyaml
    - numpy
    - h5py
    - psutil
    - matplotlib
    - scipy
    - pandas
    - plotly
    - dash
    - python=3.7
    - requests
    - plotly
    - plotly-orca
